name: Comment_on_pullrequest

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment_on_pullrequest
        if: ${{ (github.event.pull_request.user.login == 'jge162') && !(github.actor == 'dependabot[bot]') }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Thank you for opening this Pull Request. The team will review it when time permits. **Please allow 24 hours**
          message-failure: |
            Uh oh! An error ocurred.
          message-id: add-pr-comment
          repo-token: ${{ secrets.WORKFLOW_SECRET }}
          allow-repeats: true
          status: success
