on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ (github.event.pull_request.user.login != 'jge162') && (github.actor != 'dependabot[bot]') }}
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: | 
          Hi! Welcome to Python_Scripts, this is your first time opening an issue!
        pr-message: | 
          Hello! Welcome to Python_Scripts, this is your first time opening a Pull Request!
